version: '3'
services:
  movies:
    image: dipeshs28/paytmmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  train:
    image: dipeshs28/dth:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  dth:
    image: dipeshs28/recharge:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3

  recharge:
    image: dipeshs28/first:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
